# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='file_name',
            field=models.CharField(default='mars.jpg', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='pics/static/images'),
        ),
    ]
